'Declare variables to be used
Dim swApp As SldWorks.SldWorks
Dim swmodel As SldWorks.ModelDoc2
Dim swModelExt As SldWorks.ModelDocExtension
Dim ModelPath As String
Dim FullPath As String
Dim longstatus As Long
Dim longwarnings As Long
Dim errors As Long
Dim config As SldWorks.Configuration
Dim cusPropMgr As SldWorks.CustomPropertyManager
Dim RevValue As String

Sub main()

'Connect to SOLIDWORKS
Set swApp = Application.SldWorks

'Connect to open model
Set swmodel = swApp.ActiveDoc

'Connect to Model Extension
Set swModelExt = swmodel.Extension

'Get Revision value
GetRevision swmodel, swApp

'Get file path
ModelPath = swmodel.GetPathName

'trim off file extension
FullPath = Left(ModelPath, Len(ModelPath) - 7)

'Change Export Quality
ChangeQuality

' Save As       Change the extension ".stl" below to switch to any export format
longstatus = swModelExt.SaveAs(FullPath & "-" & RevValue & ".stl", 0, 2, Nothing, errors, longwarnings)

End Sub

Sub ChangeQuality()

'set user export options to high resolution STL Export
longstatus = swApp.SetUserPreferenceIntegerValue(swUserPreferenceIntegerValue_e.swSTLQuality, swSTLQuality_Custom)
longstatus = swApp.SetUserPreferenceIntegerValue(swUserPreferenceDoubleValue_e.swSTLDeviation, 0.00013)
longstatus = swApp.SetUserPreferenceIntegerValue(swUserPreferenceDoubleValue_e.swSTLAngleTolerance, 0.5)

End Sub

Sub GetRevision(swmodel As SldWorks.ModelDoc2, swApp As SldWorks.SldWorks)


Set config = swmodel.GetActiveConfiguration

'Get the property manager for the configuration
Set cusPropMgr = config.CustomPropertyManager

'Get the revision property
RevValue = cusPropMgr.Get("Revision")

End Sub

